name: build android apk
on: [push]
jobs :
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name:build with buildozer
uses: artemsbulgakov/buildozer-action@v/1
with:
buildozer_version: master
id: buildozer
- name: upload apk
 uses: actions/upload-artifact@v3 
 with:
   name: package
   path: ${{ steps.buildozer.outputs.filename }}
