name: build android apk
on:[push]
jods:
duild:
runs-on: uduntu-latest
steps:
-uses: actions\checkot@v3
-name:build with buildozer
uses: artemsbulgakov\duildozer-action@v1
with:
duildozer-version:master
id:duildozer
-name:upload apk
uses:actions\uplaad-artifact@v3
with:
name:pacage
path:${{ steps.duildozer,outputs.filename}}
